#+TITLE: CaPPA - The Catalysis Preprint Archive
#+author: John Kitchin
#+options: toc:nil


* About CaPPA
The Catalysis Preprint Archive provides access to preprints of published papers in the field of catalysis. The goal is to provide a curated, aggregated repository of the preprints, prepared by the authors. These repositories will ideally contain:
- README.org :: A description of the preprint repository
- manuscript source file :: A LaTeX, org-mode, or MS Word document, and files required to build it.
- supporting information :: Data and analysis files

Our goal is to make sharing our work and data as easy as possible.

CaPPA is accessible through this site, through Emacs, and eventually through Python and Ruby.

* Available preprints
Each link below will take you to the preprint page, which has more information about the preprint.

#+name: preprints
#+BEGIN_SRC emacs-lisp :exports results
(add-to-list 'load-path "/Users/jkitchin/Catalysis-Preprint-Archive/melpa")
(require 'cappa-utils)

(load-file "/Users/jkitchin/Dropbox/kitchingroup/jmax/init.el")

(append '(("Preprint" "DOI" "Citation") hline)
	(loop for (label . props) in (package-build-archive-alist)
	      with doi = nil
	      with journal = nil
	      with authors = nil
	      with desc = nil
	      with year = nil
	      with bibtex = nil
	      with citation = nil
	      do
	      (setq desc (elt props 2))
	      (with-current-buffer
		  (find-file-noselect
		   (expand-file-name
		    (format "%s/%s.el" label label)
		    package-build-working-dir))


		(setq doi (lm-header "doi")
		      journal (lm-header "journal")
		      authors (mapconcat 'identity  (split-string  (lm-header "author") "\n") ", ")
		      year (lm-header "year")
		      bibtex (lm-header "bibtex")))
	      (when bibtex
		(with-temp-buffer
		  (insert bibtex)
		  (bibtex-beginning-of-entry)
		  (setq citation (org-ref-bib-citation))))
	      collect (list
		       (format "[[./preprints/%s-%s.%s.html][%s]]"
			       label
			       (nth 0 (elt props 0))
			       (nth 1 (elt props 0))
			       label)
		       (if doi (format "[[doi:%s][doi]]" doi) "")
		       citation)))

#+END_SRC



#+CAPTION: These are the preprints.
#+ATTR_HTML: :border 2 :rules all :frame border
#+RESULTS: preprints
| Preprint        | DOI | Citation                                                                                                                                                                                                                                                        |
|-----------------+-----+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| [[./preprints/kitchingroup-9-20160131.1849.html][kitchingroup-9]]  | [[doi:10.1103/PhysRevLett.93.156801][doi]] | , "", , : ()                                                                                                                                                                                                                                                    |
| [[./preprints/kitchingroup-7-20160131.1850.html][kitchingroup-7]]  | [[doi:10.1063/1.1737365][doi]] | Kitchin, J. R. and N{\o}rskov, J. K. and Barteau, M. A. and Chen, J. G., "Modification of the Surface Electronic and Chemical Properties of {Pt}(111) By Subsurface 3d Transition Metals", Journal of Chemical Physics, 120:10240-10246 (2004)                  |
| [[./preprints/kitchingroup-57-20160131.1841.html][kitchingroup-57]] | [[doi:10.1021/acscatal.5b00538][doi]] | Kitchin, John R., "Examples of Effective Data Sharing in Scientific Publishing", ACS Catalysis, 5:3894-3899 (2015)                                                                                                                                              |
| [[./preprints/kitchingroup-46-20160131.1840.html][kitchingroup-46]] | [[doi:10.1021/ja5015986][doi]] | Ethan L. Demeter and Shayna L. Hilburg and Newell R. Washburn and Terrence J. Collins and John R. Kitchin, "Electrocatalytic Oxygen Evolution With an Immobilized {TAML} Activator", J. Am. Chem. Soc., 136:5603-5606 (2014)                                    |
| [[./preprints/kitchingroup-43-20160131.1838.html][kitchingroup-43]] | [[doi:10.1007/s11244-013-0166-3][doi]] | Spencer D. Miller and Vladimir V. Pushkarev and Andrew J. Gellman and John R. Kitchin, "Simulating Temperature Programmed Desorption of Oxygen on {P}t(111) Using {DFT} Derived Coverage Dependent Desorption Barriers", Topics in Catalysis, 57:106-117 (2014) |
| [[./preprints/cappa-20160130.1736.html][cappa]]           |     | Spencer D. Miller and Vladimir V. Pushkarev and Andrew J. Gellman and John R. Kitchin, "Simulating Temperature Programmed Desorption of Oxygen on {P}t(111) Using {DFT} Derived Coverage Dependent Desorption Barriers", Topics in Catalysis, 57:106-117 (2014) |

* Install CaPPA in Emacs

To access the CaPPA archive in Emacs add this to an init file.

#+BEGIN_SRC emacs-lisp :exports code
(add-to-list 'package-archives
	     '("CaPPA" . "http://catalysis-preprint-archive.github.io/preprints/") t)
#+END_SRC

Then, you can install the `cappa' package and preprints using the Emacs package installer.

Use the `cappa' command to list the installed preprints, and preprints available for installation through Emacs. This is a work in progress.

* Submitting a preprint
The basic process to submit a preprint to CaPPA is to create a preprint repository (e.g. https://github.com/KitchinHUB/kitchingroup-57). Then, send a "recipe" file (e.g. https://github.com/Catalysis-Preprint-Archive/melpa/blob/cappa/recipes/kitchingroup-57) to jkitchin@andrew.cmu.edu.

I am working on streamlining this process.

* Interested in developing?
** User experience
If you can contribute ideas on how to make this work well, they are welcome.
** Web interface to CaPPA
I can always use help making the Web interface better.

** Alternate interfaces to CaPPA
You can access data about the archives here [[./archive.json]] and the recipes at [[./recipes.json]]. You can build a library in Python or Ruby to access everything from those I think. Let me know if you do that or want help doing it.

Here is a typical entry for the archive.json file
#+BEGIN_SRC text
"label":{"ver":[major,minor],"deps":null,"desc":"Some descriptive text","type":"tar","props":{"authors":{"John Kitchin":"jkitchin@andrew.cmu.edu"},"maintainer":{"John Kitchin":"jkitchin@andrew.cmu.edu"}}}


"kitchingroup-9":{"ver":[20160131,1150],"deps":null,"desc":"preprint","type":"tar","props":{"authors":{"John Kitchin":"jkitchin@andrew.cmu.edu"},"maintainer":{"John Kitchin":"jkitchin@andrew.cmu.edu"}}}
#+END_SRC

Preprints as tar archive files in /preprints/label-major.minor.tar.

A typical recipe entry is:
#+BEGIN_SRC text
"kitchingroup-9":{"fetcher":"github","repo":"KitchinHUB/kitchingroup-9","files":["*"]}
#+END_SRC
** Roadmap
- Search
- Sortable preprint table
- Analytics on downloads like MELPA does

* Acknowledgements
CaPPA is built on the shoulders of [[http://melpa.org][MELPA]].
